### ISSUE TITLE
报错D:\HeavenlyBypassAV-main\49bcd153-0f35-45cf-92c6-1384feaa7bbb.log

### ISSUE THREAD

**Issue by Devil-QAQ** [baigae/HeavenlyBypassAV#2]
报错
D:\HeavenlyBypassAV-main
λ Heavenly.exe
successfully.
An error occurred during the compilation process:
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30154 版
版权所有(C) Microsoft Corporation。保留所有权利。

successfully.
An error occurred during the compilation process:
Unable to load file: "D:\HeavenlyBypassAV-main\49bcd153-0f35-45cf-92c6-1384feaa7bbb.log"

An error occurred during the compilation process:
[13760] Failed to execute script 'sigthief' due to unhandled exception!
Traceback (most recent call last):
  File "sigthief.py", line 248, in <module>
  File "sigthief.py", line 120, in writeCert
  File "sigthief.py", line 18, in gather_file_info_win
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\HeavenlyBypassAV-main\\49bcd153-0f35-45cf-92c6-1384feaa7bbb.log'

**Comment by baigae** [comment]
找不到D:\HeavenlyBypassAV-main\49bcd153-0f35-45cf-92c6-1384feaa7bbb.log这个文件，没有编译出来

**Comment by Devil-QAQ** [comment]
是我的vc环境有问题吗

**Comment by baigae** [comment]
对的
